#!/bin/bash
cat <<EOF > kong-new.yaml
_format_version: "3.0"
_konnect:
  runtime_group_name: default
services:
- connect_timeout: 60000
  host: countries.trevorblades.com
  name: CountryQL
  path: /
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: QueryCountries
    path_handling: v0
    paths:
    - /query
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
EOF